default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
#  This, while it's said in https://www.sqlite.org/inmemorydb.html
#  works, rails can't recognize this format and will create a file
#  named production.sqlite3?mode=memory&cache=shared
#  A work around I can think of is when deploy this rails app,
#  mount the db file in a mem filesystem.
#  database: file:db/production.sqlite3?mode=memory&cache=shared
  database: db/production.sqlite3